-- CREATE TABLE IF NOT EXISTS CALCULATOR (
-- PRODUCT_ID TEXT,
-- PRODUCT_NAME TEXT,
-- SUPPLIER_ID TEXT,
-- CATEGORY_ID TEXT,
-- UNIT TEXT,
-- PRICE REAL 
-- );

-- INSERT INTO CALCULATOR ( PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES
-- ( '1', 'SHOES', '1', '1', '10 BOXES*20 BAGS', 18),
-- ( '2', 'EARRING', '1', '2', '11 BOXES*23 BAGS', 19),
-- ( '3', 'PEN', '1', '2', '10 BOXES*20 BAGS', 20),
-- ( '1', 'BRACELETS', '1', '2', '3 BOXES*9 BAGS', 21),
-- ( '1', 'ANKLETS', '1', '2', '4 BOXES*20 BAGS', 22);
-- SELECT * FROM CALCULATOR
-- SELECT MIN(Price)
-- FROM CALCULATOR;

-- SELECT MAX(Price)
-- FROM CALCULATOR;
SELECT COUNT(PRODUCT_ID) AS Product_Count

FROM CALCULATOR;
SELECT AVG(PRICE) AS Average_Price

FROM CALCULATOR;

SELECT SUM(PRICE) AS Total_Price

FROM CALCULATOR;

SELECT COUNT(PRODUCT_ID)

FROM CALCULATOR

WHERE Price > 20;





